import type { SupabaseClient } from '@supabase/supabase-js'
import type { Database } from '@/types/database'
import type {
  ITestCaseService,
  ITestCaseGenerator,
  TestCaseData,
  GeneratedTestCase,
  ServiceResult,
} from '../contracts'

type TestCaseInsert = Database['public']['Tables']['test_cases']['Insert']

/**
 * Test Case Service Implementation
 *
 * Handles test case CRUD operations and auto-generation logic.
 * Used by both dashboard (UAT management) and tester portal.
 */
export class TestCaseService implements ITestCaseService {
  constructor(private supabase: SupabaseClient<Database>) {}

  async getTestCasesForStory(
    storyId: string,
    includeArchived = false
  ): Promise<ServiceResult<TestCaseData[]>> {
    let query = this.supabase
      .from('test_cases')
      .select('*')
      .eq('story_id', storyId)
      .order('created_at', { ascending: false })

    if (!includeArchived) {
      query = query.eq('is_archived', false)
    }

    const { data, error } = await query

    if (error) {
      return { success: false, error: error.message }
    }

    return { success: true, data: data as TestCaseData[] }
  }

  async hasTestCases(storyId: string): Promise<ServiceResult<boolean>> {
    const { data, error } = await this.supabase
      .from('test_cases')
      .select('test_case_id')
      .eq('story_id', storyId)
      .eq('is_archived', false)
      .limit(1)

    if (error) {
      return { success: false, error: error.message }
    }

    return { success: true, data: (data?.length ?? 0) > 0 }
  }

  async saveGeneratedTestCases(
    storyId: string,
    programId: string,
    testCases: GeneratedTestCase[],
    createdBy: string
  ): Promise<ServiceResult<{ count: number }>> {
    const insertData: TestCaseInsert[] = testCases.map(tc => ({
      story_id: storyId,
      program_id: programId,
      title: tc.title,
      description: tc.description,
      preconditions: tc.preconditions,
      test_steps: JSON.stringify(tc.test_steps),
      expected_results: tc.expected_results,
      test_type: tc.test_type,
      priority: tc.priority,
      is_ai_generated: true,
      ai_model_used: 'claude-sonnet-4-20250514',
      status: 'draft',
      created_by: createdBy,
    }))

    const { error } = await this.supabase
      .from('test_cases')
      .insert(insertData)

    if (error) {
      return { success: false, error: error.message }
    }

    return { success: true, data: { count: testCases.length } }
  }

  async markAutoGenerated(storyId: string): Promise<ServiceResult> {
    const { error } = await this.supabase
      .from('user_stories')
      .update({ test_cases_auto_generated_at: new Date().toISOString() })
      .eq('story_id', storyId)

    if (error) {
      return { success: false, error: error.message }
    }

    return { success: true }
  }
}

/**
 * Claude Test Case Generator Implementation
 *
 * Uses Claude API to generate test cases from story details.
 */
export class ClaudeTestCaseGenerator implements ITestCaseGenerator {
  async isAvailable(): Promise<boolean> {
    return !!process.env.ANTHROPIC_API_KEY
  }

  async generate(story: {
    title: string
    description: string
    acceptanceCriteria?: string
    programName?: string
    category?: string
  }): Promise<ServiceResult<GeneratedTestCase[]>> {
    // Dynamic import to avoid loading AI deps when not needed
    const { callClaude, parseJSONResponse } = await import('@/lib/ai/client')
    const {
      TEST_CASE_GENERATION_SYSTEM_PROMPT,
      TEST_CASE_GENERATION_USER_PROMPT,
    } = await import('@/lib/ai/prompts')

    const result = await callClaude({
      systemPrompt: TEST_CASE_GENERATION_SYSTEM_PROMPT,
      userPrompt: TEST_CASE_GENERATION_USER_PROMPT({
        title: story.title,
        description: story.description,
        acceptanceCriteria: story.acceptanceCriteria,
        programName: story.programName,
        category: story.category,
      }),
      config: {
        maxTokens: 4096,
        temperature: 0.5,
      },
    })

    if (!result.success || !result.content) {
      return { success: false, error: result.error || 'Failed to generate test cases' }
    }

    const testCases = parseJSONResponse<GeneratedTestCase[]>(result.content)
    if (!testCases || !Array.isArray(testCases)) {
      return { success: false, error: 'Failed to parse generated test cases' }
    }

    return { success: true, data: testCases }
  }
}

/**
 * Stub generator for deployments without AI
 */
export class ManualTestCaseGenerator implements ITestCaseGenerator {
  async isAvailable(): Promise<boolean> {
    return false
  }

  async generate(): Promise<ServiceResult<GeneratedTestCase[]>> {
    return {
      success: false,
      error: 'AI test case generation is not available in this deployment',
    }
  }
}

/**
 * Factory function to get the appropriate generator
 */
export function getTestCaseGenerator(): ITestCaseGenerator {
  if (process.env.ANTHROPIC_API_KEY) {
    return new ClaudeTestCaseGenerator()
  }
  return new ManualTestCaseGenerator()
}
