import type { TestCaseStatus, TestType } from '@/types/database'
import type { ServiceResult } from './story-contract'

/**
 * Generated test case from AI
 */
export interface GeneratedTestCase {
  title: string
  description: string
  preconditions: string | null
  test_steps: Array<{
    step_number: number
    action: string
    expected_result: string
  }>
  expected_results: string
  test_type: TestType
  priority: string
}

/**
 * Test case data
 */
export interface TestCaseData {
  test_case_id: string
  story_id: string
  program_id: string
  title: string
  description: string | null
  preconditions: string | null
  test_steps: string // JSON stringified
  expected_results: string | null
  test_type: string
  priority: string
  status: TestCaseStatus
  is_ai_generated: boolean
  ai_model_used: string | null
  is_archived: boolean
  created_by: string
  created_at: string
  updated_at: string
}

/**
 * Test Case Service Contract
 *
 * Defines operations for managing test cases.
 */
export interface ITestCaseService {
  /**
   * Get test cases for a story
   */
  getTestCasesForStory(
    storyId: string,
    includeArchived?: boolean
  ): Promise<ServiceResult<TestCaseData[]>>

  /**
   * Check if story has existing test cases
   */
  hasTestCases(storyId: string): Promise<ServiceResult<boolean>>

  /**
   * Save generated test cases
   */
  saveGeneratedTestCases(
    storyId: string,
    programId: string,
    testCases: GeneratedTestCase[],
    createdBy: string
  ): Promise<ServiceResult<{ count: number }>>

  /**
   * Update auto-generation timestamp on story
   */
  markAutoGenerated(storyId: string): Promise<ServiceResult>
}

/**
 * Test Case Generator Contract
 *
 * Defines AI test case generation.
 * Can be swapped for different AI providers or disabled.
 */
export interface ITestCaseGenerator {
  /**
   * Check if generation is available
   */
  isAvailable(): Promise<boolean>

  /**
   * Generate test cases for a story
   */
  generate(story: {
    title: string
    description: string
    acceptanceCriteria?: string
    programName?: string
    category?: string
  }): Promise<ServiceResult<GeneratedTestCase[]>>
}
